#!/usr/bin/env bash

set -euo pipefail

TRINO_CONTAINER="${TRINO_CONTAINER:-tf2-trino}"
TRINO_HOST="${TRINO_HOST:-tf2-trino}"
TRINO_PORT="${TRINO_PORT:-8080}"
TRINO_USER="${TRINO_USER:-ml_trainer}"
TRINO_CATALOG="${TRINO_CATALOG:-tf2}"
TRINO_SCHEMA="${TRINO_SCHEMA:-default}"
TRINO_HTTP_SCHEME="${TRINO_HTTP_SCHEME:-http}"
MODEL_VERSION="${MODEL_VERSION:-v1.0.0}"
TRAIN_RATIO="${TRAIN_RATIO:-0.8}"
SNAPSHOT_ID="${SNAPSHOT_ID:-}"
IMAGE_NAME="${ML_TRAINER_IMAGE:-logs-explorer-ml-trainer:latest}"
NETWORK_NAME="${ML_TRAINER_NETWORK:-logs-explorer}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
DOCKERFILE="$ROOT_DIR/infra/ml/Dockerfile"
TRAINING_CODE_VERSION="${TRAINING_CODE_VERSION:-$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo unknown)}"
FEATURE_SQL_VERSION="${FEATURE_SQL_VERSION:-$TRAINING_CODE_VERSION}"
WIN_POLICY_MIN_PRECISION="${WIN_POLICY_MIN_PRECISION:-0.60}"
WIN_POLICY_MIN_RECALL="${WIN_POLICY_MIN_RECALL:-0.55}"
TILT_POLICY_MIN_PRECISION="${TILT_POLICY_MIN_PRECISION:-0.75}"
TILT_POLICY_MIN_RECALL="${TILT_POLICY_MIN_RECALL:-0.95}"
GATE_WIN_MIN_F1="${GATE_WIN_MIN_F1:-0.66}"
GATE_WIN_MAX_BRIER="${GATE_WIN_MAX_BRIER:-0.20}"
GATE_WIN_MIN_FOLD_F1="${GATE_WIN_MIN_FOLD_F1:-0.60}"
GATE_IMPACT_MAX_RMSE="${GATE_IMPACT_MAX_RMSE:-20.00}"
GATE_IMPACT_MAX_MAE="${GATE_IMPACT_MAX_MAE:-16.00}"
GATE_IMPACT_MAX_FOLD_RMSE="${GATE_IMPACT_MAX_FOLD_RMSE:-22.00}"
GATE_TILT_MIN_F1="${GATE_TILT_MIN_F1:-0.85}"
GATE_TILT_MAX_BRIER="${GATE_TILT_MAX_BRIER:-0.02}"
GATE_TILT_MIN_RECALL="${GATE_TILT_MIN_RECALL:-0.95}"
GATE_TILT_MAX_FOLD_F1_STD="${GATE_TILT_MAX_FOLD_F1_STD:-0.03}"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -q "^${TRINO_CONTAINER}$"; then
  echo "Trino container '${TRINO_CONTAINER}' is not running." >&2
  echo "Start it with: docker compose -f infra/trino/docker-compose.yml up -d" >&2
  exit 1
fi

echo "== TF2 ML baseline training =="
echo "Trino container: ${TRINO_CONTAINER}"
echo "Trino endpoint: ${TRINO_HTTP_SCHEME}://${TRINO_HOST}:${TRINO_PORT}"
echo "Model version: ${MODEL_VERSION}"
echo "Image: ${IMAGE_NAME}"
echo "Network: ${NETWORK_NAME}"
echo

docker build -t "$IMAGE_NAME" -f "$DOCKERFILE" "$ROOT_DIR"

docker run --rm \
  --network "$NETWORK_NAME" \
  -v "$ROOT_DIR:/workspace" \
  -w /workspace \
  -e TRINO_HOST="$TRINO_HOST" \
  -e TRINO_PORT="$TRINO_PORT" \
  -e TRINO_USER="$TRINO_USER" \
  -e TRINO_CATALOG="$TRINO_CATALOG" \
  -e TRINO_SCHEMA="$TRINO_SCHEMA" \
  -e TRINO_HTTP_SCHEME="$TRINO_HTTP_SCHEME" \
  -e MODEL_VERSION="$MODEL_VERSION" \
  -e TRAIN_RATIO="$TRAIN_RATIO" \
  -e SNAPSHOT_ID="$SNAPSHOT_ID" \
  -e TRAINING_CODE_VERSION="$TRAINING_CODE_VERSION" \
  -e FEATURE_SQL_VERSION="$FEATURE_SQL_VERSION" \
  -e WIN_POLICY_MIN_PRECISION="$WIN_POLICY_MIN_PRECISION" \
  -e WIN_POLICY_MIN_RECALL="$WIN_POLICY_MIN_RECALL" \
  -e TILT_POLICY_MIN_PRECISION="$TILT_POLICY_MIN_PRECISION" \
  -e TILT_POLICY_MIN_RECALL="$TILT_POLICY_MIN_RECALL" \
  -e GATE_WIN_MIN_F1="$GATE_WIN_MIN_F1" \
  -e GATE_WIN_MAX_BRIER="$GATE_WIN_MAX_BRIER" \
  -e GATE_WIN_MIN_FOLD_F1="$GATE_WIN_MIN_FOLD_F1" \
  -e GATE_IMPACT_MAX_RMSE="$GATE_IMPACT_MAX_RMSE" \
  -e GATE_IMPACT_MAX_MAE="$GATE_IMPACT_MAX_MAE" \
  -e GATE_IMPACT_MAX_FOLD_RMSE="$GATE_IMPACT_MAX_FOLD_RMSE" \
  -e GATE_TILT_MIN_F1="$GATE_TILT_MIN_F1" \
  -e GATE_TILT_MAX_BRIER="$GATE_TILT_MAX_BRIER" \
  -e GATE_TILT_MIN_RECALL="$GATE_TILT_MIN_RECALL" \
  -e GATE_TILT_MAX_FOLD_F1_STD="$GATE_TILT_MAX_FOLD_F1_STD" \
  "$IMAGE_NAME"
